[package]
name = "rt3r"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.tes3]
git = "https://github.com/Greatness7/tes3"
branch = "dev"

[dependencies]
rand = "0.8.3"